# Config file for automatic testing at travis-ci.org
language: python

os:
    - linux

python:
  - 3.6
  - 3.5
  - 3.4


install:
  - pip install setuptools
  - pip install -e .
  - pip install --upgrade pytest
  - pip install codecov
  - pip install pytest-cov

cache: pip

script:
    - pytest tests --runslow -v --cov=pathpy
    - codecov

